# Harmony Jekyll theme general configurations

# Base URL
baseurl: "https://dadamonad.github.io/"

# Site live URL
url: ""

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "DadaMonad's Blog"
  # Little description about your site
  description: Web, OT, Yatta, Polymer and other stuff
  meta_description: > # 
   Blog about my development on Yatta and real-time web applications
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author:
    name: Kevin Jahns
    email: kevin.jahns@rwth-aachen.de
    url: https://dadamonad.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-57560172-1

  # Profile links, leave blank to ignore
  social: 
    github: DadaMonad
    twitter: 
    facebook: 
    gplus: u/0/110297010634240861782/
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
kramdown:
  input: GFM
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        pretty
relative_permalinks: false
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - modules/Yatta/node_modules
  - modules/Yatta-Connectors/node_modules

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
