# Harmony Jekyll theme general configurations

# Base URL
baseurl: "http://y-js.org/"

# Site live URL
url: ""

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "Welcome to Yjs!"
  # Little description about your site
  description: The one true shared editing framework
  meta_description: > # 
   Blog about my development on yjs and real-time web applications
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author:
    name: Kevin Jahns
    email: kevin.jahns@rwth-aachen.de
    url: y-js.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-57560172-1

  # Profile links, leave blank to ignore
  social: 
    github: y-js
    twitter: 
    facebook: 
    gplus: #u/0/110297010634240861782/
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
kramdown:
  input: GFM
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        none
relative_permalinks: false
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - modules/yjs/node_modules
  - modules/y-list/node_modules
  - modules/y-xmpp/node_modules
  - modules/y-webrtc/node_modules
  - modules/y-selections/node_modules
  - modules/y-xml/node_modules
  - modules/y-text/node_modules
  - modules/meme-together/node_modules

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
